"""F-09 Reason Code 人类解释层（**纯 presentation catalog**）。

边界（人类裁决 / Slice 4 §2）：

- 原始 `reason_code` **永远保留**（本模块只做附加解释，绝不替换 / 改写 code）；
- catalog **不参与任何决策**（RiskGate / Readiness / Execution authority / Governor 都不 import 本模块）；
- 未收录的 code ⇒ 返回 `raw code + 暂无解释`，**不猜语义**；
- UI / API / Assistant / CLI 复用同一 catalog（单一来源，避免多处硬编码文案）。

本模块只依赖标准库：不 import 任何领域模块、不含阈值、不产生事实。
"""

from __future__ import annotations

from dataclasses import dataclass

#: 解释的领域分区（与产品直接显示的来源一致）
DOMAINS: tuple[str, ...] = (
    "market", "prediction", "readiness", "hwm", "execution", "rate_limit",
    "reconciliation", "accounting", "risk", "orchestrator", "config",
    #: closure Slice 5：operational posture
    "network", "auth", "logging", "retention", "process",
    "unknown",
)

#: 未收录 code 的固定文案（绝不猜测业务语义）
UNKNOWN_TITLE = "暂无解释"
UNKNOWN_EXPLANATION = "catalog 未收录该 reason code；保留原始 code，未推断语义。"
UNKNOWN_EXPLANATION_EN = ("this reason code is not in the catalog; the raw code is preserved "
                          "and its semantics are not guessed")
UNKNOWN_NEXT_STEP = "查阅产生该 code 的 Owner（见 blocker.source_ref / 原始事实）。"
UNKNOWN_NEXT_STEP_EN = "open the owning component that emitted the code (see source_ref / raw facts)"


@dataclass(frozen=True, slots=True)
class ReasonExplanation:
    """一个 reason code 的人类可读解释（presentation-only）。"""

    reason_code: str
    title: str
    explanation: str
    severity: str
    suggested_next_step: str
    domain: str
    title_en: str = ""
    explanation_en: str = ""
    suggested_next_step_en: str = ""
    catalogued: bool = True

    def __post_init__(self) -> None:
        if not isinstance(self.reason_code, str) or not self.reason_code:
            raise ValueError("ReasonExplanation.reason_code must be a non-empty string")
        for name in ("title", "explanation", "severity", "suggested_next_step", "domain"):
            value = getattr(self, name)
            if not isinstance(value, str) or not value:
                raise ValueError(f"ReasonExplanation.{name} must be a non-empty string")

    def to_payload(self) -> dict[str, object]:
        return {
            "reason_code": self.reason_code,
            "title": self.title,
            "explanation": self.explanation,
            "severity": self.severity,
            "suggested_next_step": self.suggested_next_step,
            "domain": self.domain,
            "title_en": self.title_en or self.title,
            "explanation_en": self.explanation_en or self.explanation,
            "suggested_next_step_en": self.suggested_next_step_en or self.suggested_next_step,
            "catalogued": self.catalogued,
        }


def _entry(code: str, *, title: str, explanation: str, severity: str, next_step: str, domain: str,
           title_en: str = "", explanation_en: str = "", next_step_en: str = "") -> tuple[str, ReasonExplanation]:
    return code, ReasonExplanation(reason_code=code, title=title, explanation=explanation,
                                   severity=severity, suggested_next_step=next_step, domain=domain,
                                   title_en=title_en, explanation_en=explanation_en,
                                   suggested_next_step_en=next_step_en)


#: catalog 条目：`reason_code -> ReasonExplanation`（单一来源）
_ENTRIES: tuple[tuple[str, ReasonExplanation], ...] = (
    # ------------------------------------------------------------------ market
    _entry("MARKET_UNHEALTHY", title="行情不可用", severity="BLOCKING", domain="market",
           explanation="盘口 / 数据质量门未通过（HEALTHY 之外），策略不新增暴露。",
           next_step="查看 System → Health 的 market / book health 与 gap / resync 时间线。",
           title_en="Market not healthy",
           explanation_en="the book / data-quality gate is not HEALTHY, so new exposure is not allowed",
           next_step_en="open System → Health (market / book health, gap / resync timeline)"),
    _entry("MARKET_NOT_TRADEABLE", title="行情不可交易", severity="BLOCKING", domain="market",
           explanation="market state 的 tradeable 为 false（warm-up 未完成或窗口覆盖不足）。",
           next_step="等待 5 分钟事件窗口覆盖（history_ready）并确认盘口健康。",
           title_en="Market not tradeable",
           explanation_en="market state tradeable is false (warm-up incomplete or window coverage short)",
           next_step_en="wait for the 5-minute history window (history_ready) and confirm book health"),
    _entry("MARKET_NOT_READY", title="市场事实未就绪", severity="BLOCKING", domain="market",
           explanation="readiness 要求的新鲜市场事实（锚定 / mark / feed age / aggTrade）不满足。",
           next_step="查看 System → Readiness 的 market 相关 reason。",
           title_en="Market facts not ready",
           explanation_en="the fresh market facts required by readiness (anchor, mark, feed age, aggTrade) are absent",
           next_step_en="inspect the market-related reasons in System → Readiness"),
    # ------------------------------------------------------------------ prediction
    _entry("PREDICTION_STALE", title="预测过期/不可用", severity="BLOCKING", domain="prediction",
           explanation="预测缺失或过期；新增暴露被禁止（降险仍允许）。",
           next_step="查看 Activity → Prediction 与 System → Health 的 prediction provider 状态。",
           title_en="Prediction stale / unavailable",
           explanation_en="no fresh prediction; new increasing exposure is blocked (de-risking stays allowed)",
           next_step_en="open Activity → Prediction and System → Health (prediction provider)"),
    _entry("PREDICTION_PROVIDER_UNKNOWN", title="预测 provider 未知", severity="DEGRADED", domain="prediction",
           explanation="未接入 prediction runtime 或未取到 provider 状态（UNKNOWN，不是 healthy）。",
           next_step="确认 prediction runtime 是否 attach；不要把它当作健康。",
           title_en="Prediction provider unknown",
           explanation_en="no prediction runtime attached or no provider status available (UNKNOWN != healthy)",
           next_step_en="confirm whether a prediction runtime is attached; do not read this as healthy"),
    _entry("PREDICTION_PROVIDER_BACKING_OFF", title="预测 provider 退避中", severity="DEGRADED",
           domain="prediction",
           explanation="provider 连续失败后进入 backoff，短期不会再有新预测。",
           next_step="查看 prediction submissions 日志与 error 分类。",
           title_en="Prediction provider backing off",
           explanation_en="the provider is in backoff after repeated failures; expect no fresh prediction soon",
           next_step_en="inspect the prediction submission log and failure classes"),
    # ------------------------------------------------------------------ readiness
    _entry("RECOVERY_NOT_READY", title="启动恢复未完成", severity="BLOCKING", domain="readiness",
           explanation="本地订单 / 持仓 / 近期成交与交易所在当前事实边界尚未收敛。",
           next_step="重跑 recovery 并确认 RECOVERED（断线后必须重走完整流程）。",
           title_en="Recovery not ready",
           explanation_en="local orders / positions / recent fills have not converged with the exchange",
           next_step_en="re-run recovery and confirm RECOVERED (a reconnect requires the full flow again)"),
    _entry("PRIVATE_STREAM_NOT_READY", title="私有流未就绪", severity="BLOCKING", domain="readiness",
           explanation="listenKey / user stream 未 ACTIVE 或连续性未建立。",
           next_step="检查 private stream 状态与 discontinuity 事件。",
           title_en="Private stream not ready",
           explanation_en="the listenKey / user stream is not ACTIVE or continuity was not established",
           next_step_en="check the private stream state and discontinuity events"),
    _entry("ACCOUNT_CANNOT_TRADE", title="账户不可交易", severity="BLOCKING", domain="readiness",
           explanation="交易所账户状态不允许交易（canTrade=false 或模式不符）。",
           next_step="在交易所侧确认账户状态 / 模式（one-way + USDT-M）。",
           title_en="Account cannot trade",
           explanation_en="the exchange account state does not allow trading (canTrade=false or wrong mode)",
           next_step_en="confirm account state / mode on the exchange (one-way + USDT-M)"),
    _entry("AVAILABLE_BALANCE_UNKNOWN", title="可用余额未知", severity="BLOCKING", domain="readiness",
           explanation="交易所可用余额事实缺失（UNKNOWN，不是 0）。",
           next_step="确认 account snapshot 是否取得 availableBalance。",
           title_en="Available balance unknown",
           explanation_en="the exchange available-balance fact is missing (UNKNOWN, not zero)",
           next_step_en="confirm the account snapshot delivered availableBalance"),
    _entry("AVAILABLE_BALANCE_STALE", title="可用余额过期", severity="BLOCKING", domain="readiness",
           explanation="account snapshot 年龄超过允许阈值。",
           next_step="刷新 account snapshot 后重新收集 readiness evidence。",
           title_en="Available balance stale",
           explanation_en="the account snapshot is older than the allowed age",
           next_step_en="refresh the account snapshot and re-collect readiness evidence"),
    _entry("HISTORICAL_DAILY_PNL_UNKNOWN", title="当日盈亏未知", severity="BLOCKING", domain="readiness",
           explanation="当日已实现盈亏无法完整取得（缺 income 覆盖或未分类流水）。",
           next_step="检查 income coverage 完整性与 unclassified 行。",
           title_en="Historical daily PnL unknown",
           explanation_en="today's realized PnL cannot be fully derived (incomplete income coverage)",
           next_step_en="check income coverage completeness and unclassified rows"),
    _entry("HISTORICAL_DRAWDOWN_UNKNOWN", title="历史回撤未知", severity="BLOCKING", domain="readiness",
           explanation="无可信峰值 ⇒ drawdown 未知；已配置 drawdown 限额时 fail closed。",
           next_step="初始化 / 校验 durable high-watermark（不要用当前 equity 冒充满峰值）。",
           title_en="Historical drawdown unknown",
           explanation_en="no trusted peak -> drawdown unknown; fails closed when a drawdown limit is configured",
           next_step_en="initialize / verify the durable high-watermark (never use current equity as the peak)"),
    _entry("RISK_LIMITS_NOT_CONFIGURED", title="风险限额未配置", severity="BLOCKING", domain="readiness",
           explanation="live 风险策略缺少必填字段；`RiskLimits = None` 不等于生产安全。",
           next_step="在启动配置中显式给出全部 live 风险限额。",
           title_en="Risk limits not configured",
           explanation_en="the live risk policy is missing required fields; RiskLimits=None is not production-safe",
           next_step_en="provide every live risk limit explicitly in the startup config"),
    _entry("KILL_SWITCH_NOT_OPERABLE", title="Kill switch 不可操作", severity="BLOCKING", domain="readiness",
           explanation="kill switch 非 NORMAL，且当前不满足安全操作条件。",
           next_step="确认 kill switch 状态与降险路径（cancel 不受 HALT_ALL 限制）。",
           title_en="Kill switch not operable",
           explanation_en="the kill switch is not NORMAL and safe operation is not satisfied",
           next_step_en="confirm kill-switch state and the de-risking path (cancel is never blocked by HALT_ALL)"),
    _entry("CLOCK_NOT_CALIBRATED", title="时钟未校准", severity="BLOCKING", domain="readiness",
           explanation="未测量或已过期的 server-time offset ⇒ 延迟无法做 D-036 校正。",
           next_step="重新测量 clock calibration（offset / RTT / uncertainty）。",
           title_en="Clock not calibrated",
           explanation_en="no fresh server-time offset, so latency cannot be D-036 corrected",
           next_step_en="re-measure clock calibration (offset / RTT / uncertainty)"),
    _entry("CLOCK_UNCERTAINTY_TOO_HIGH", title="时钟不确定度过高", severity="BLOCKING", domain="readiness",
           explanation="RTT 过大 ⇒ offset 不确定度超阈值；corrected lag 很小也不能通过。",
           next_step="改善网络路径（代理 / 出口）后重新校准。",
           title_en="Clock uncertainty too high",
           explanation_en="large RTT makes the offset uncertain beyond the threshold; a small corrected lag is not enough",
           next_step_en="improve the network path (proxy / egress) and re-calibrate"),
    _entry("PRIVATE_LATENCY_UNOBSERVED", title="私有延迟从未观测", severity="DEGRADED", domain="readiness",
           explanation="从未有可测私有业务事件（安静账户结构性冷启动）；不等同于未接线。",
           next_step="按 BOOTSTRAP 冷启动契约处理，或等待第一笔真实私有事件。",
           title_en="Private latency never observed",
           explanation_en="no measurable private business event has ever occurred (quiet-account cold start)",
           next_step_en="follow the BOOTSTRAP cold-start contract or wait for the first real private event"),
    _entry("PRIVATE_LATENCY_UNKNOWN", title="私有延迟未知", severity="BLOCKING", domain="readiness",
           explanation="有通道但无可用样本，无法判定私有链路延迟。",
           next_step="确认 private 流是否产生业务事件并重新收集证据。",
           title_en="Private latency unknown",
           explanation_en="the channel exists but no usable sample is available to judge private-link latency",
           next_step_en="confirm the private stream produced business events and re-collect evidence"),
    _entry("PRIVATE_LATENCY_TOO_HIGH", title="私有延迟过高", severity="BLOCKING", domain="readiness",
           explanation="corrected private lag 中位数超过阈值。",
           next_step="检查网络 / 代理与交易所侧延迟。",
           title_en="Private latency too high",
           explanation_en="the median corrected private lag exceeds the threshold",
           next_step_en="inspect network / proxy and exchange-side latency"),
    _entry("MAINNET_PRIVATE_NOT_VALIDATED", title="主网私有链路未验证", severity="BLOCKING", domain="readiness",
           explanation="主网需要独立的主网只读验收证据；testnet 证据不可转移。",
           next_step="提供主网验证记录（typed evidence）后再申请主网 scope。",
           title_en="Mainnet private link not validated",
           explanation_en="mainnet requires its own read-only validation evidence; testnet evidence does not transfer",
           next_step_en="provide a mainnet validation record (typed evidence) before requesting mainnet scope"),
    _entry("READINESS_UNKNOWN", title="就绪状态未评估", severity="BLOCKING", domain="readiness",
           explanation="尚未运行 readiness gate（没有证据）。",
           next_step="收集 readiness evidence 后重新判定。",
           title_en="Readiness not evaluated",
           explanation_en="the readiness gate has not run yet (no evidence)",
           next_step_en="collect readiness evidence and re-evaluate"),
    # ------------------------------------------------------------------ HWM
    _entry("HIGH_WATERMARK_NOT_INITIALIZED", title="峰值未初始化", severity="BLOCKING", domain="hwm",
           explanation="durable high-watermark 缺失 ⇒ drawdown 无 trusted activation point（删除文件不等于重置）。",
           next_step="满足 activation 前置条件后显式初始化并持久化。",
           title_en="High-watermark not initialized",
           explanation_en="the durable high-watermark is missing, so drawdown has no trusted activation point",
           next_step_en="explicitly initialize and persist it after the activation preconditions hold"),
    _entry("HIGH_WATERMARK_INVALID", title="峰值已失效", severity="BLOCKING", domain="hwm",
           explanation="HWM epoch 被外部资本流或显式 invalidated 置为失效。",
           next_step="按契约显式 rebase（新 epoch），不要原地抹掉历史。",
           title_en="High-watermark invalid",
           explanation_en="the HWM epoch was invalidated (external capital flow or explicit invalidation)",
           next_step_en="rebase explicitly per contract (new epoch); never erase history in place"),
    _entry("HIGH_WATERMARK_STORE_FAILED", title="峰值持久化失败", severity="BLOCKING", domain="hwm",
           explanation="peak 提升的 durable 写入失败 ⇒ 不发布新 peak（durable-before-publish）。",
           next_step="检查状态目录权限 / 磁盘后重试。",
           title_en="High-watermark store failed",
           explanation_en="the durable peak write failed, so the new peak is not published (durable-before-publish)",
           next_step_en="check state-directory permissions / disk and retry"),
    _entry("EXTERNAL_CAPITAL_FLOW_DETECTED", title="检测到外部资金流", severity="BLOCKING", domain="hwm",
           explanation="检测到 TRANSFER；deposit/withdraw 不能当作 trading peak / drawdown。",
           next_step="显式 rebase 到新 epoch。",
           title_en="External capital flow detected",
           explanation_en="a TRANSFER was detected; deposits/withdrawals must not be treated as trading peak/drawdown",
           next_step_en="rebase explicitly to a new epoch"),
    _entry("EQUITY_MISMATCH", title="权益不一致", severity="BLOCKING", domain="hwm",
           explanation="本地 equity 与交易所权益不一致（超出显式 tolerance）。",
           next_step="重新对齐账本与交易所事实（不要挑一个当真）。",
           title_en="Equity mismatch",
           explanation_en="local equity and exchange equity disagree beyond the explicit tolerance",
           next_step_en="re-align the ledger with exchange facts (do not pick one arbitrarily)"),
    # ------------------------------------------------------------------ execution
    _entry("EXECUTION_POLICY_NOT_CONFIGURED", title="执行安全策略未配置", severity="DEGRADED",
           domain="execution",
           explanation="缺少必填阈值 ⇒ ExecutionHealth 保持 UNKNOWN（不猜测、不显示 healthy）。",
           next_step="显式提供 ExecutionSafetyPolicy 的全部必填字段。",
           title_en="Execution policy not configured",
           explanation_en="required thresholds are missing, so ExecutionHealth stays UNKNOWN (never guessed healthy)",
           next_step_en="provide every required ExecutionSafetyPolicy field explicitly"),
    _entry("VENUE_FACTS_UNAVAILABLE", title="交易所限额事实不可用", severity="DEGRADED", domain="execution",
           explanation="venue limit 定义 / 当前用量缺失 ⇒ 限额状态 UNKNOWN。",
           next_step="确认 exchangeInfo/rateLimits 证据与 usage header 采集。",
           title_en="Venue facts unavailable",
           explanation_en="venue limit definition / current usage is missing, so limit state is UNKNOWN",
           next_step_en="confirm exchangeInfo/rateLimits evidence and response-header usage capture"),
    _entry("VENUE_FACTS_STALE", title="交易所限额事实过期", severity="DEGRADED", domain="execution",
           explanation="venue facts 年龄超过 venue_facts_max_age_ms。",
           next_step="刷新 venue facts 后重新投影。",
           title_en="Venue facts stale",
           explanation_en="venue facts are older than venue_facts_max_age_ms",
           next_step_en="refresh venue facts and re-project"),
    _entry("SUBMIT_LATENCY_BUDGET_EXCEEDED", title="提交延迟超预算", severity="DEGRADED", domain="execution",
           explanation="submit_to_ack p95 超过 policy budget（样本不足则保持 UNKNOWN）。",
           next_step="查看 Activity 的 ack latency 阶段与 System → Execution 的 latency 表。",
           title_en="Submit latency budget exceeded",
           explanation_en="submit_to_ack p95 exceeds the policy budget (insufficient samples stay UNKNOWN)",
           next_step_en="inspect the ack-latency stage in Activity and the latency table in System → Execution"),
    _entry("PRIVATE_LATENCY_UNHEALTHY", title="私有延迟不健康", severity="DEGRADED", domain="execution",
           explanation="私有链路延迟事实判定为不健康（来源见 blocker source_ref）。",
           next_step="对照 System → Readiness 的同一物理事实，避免重复解读。",
           title_en="Private latency unhealthy",
           explanation_en="the private-link latency fact is judged unhealthy (see source_ref)",
           next_step_en="cross-check the same physical fact in System → Readiness (F-17)"),
    _entry("EXECUTION_HEALTH_UNKNOWN", title="执行健康未知", severity="DEGRADED", domain="execution",
           explanation="required 来源为 UNKNOWN ⇒ 不得判为 HEALTHY。",
           next_step="补齐 required 来源（rate limit / venue facts / latency / exposure / reconciliation）。",
           title_en="Execution health unknown",
           explanation_en="a required source is UNKNOWN, so health must not be reported as HEALTHY",
           next_step_en="fill the required sources (rate limit / venue facts / latency / exposure / reconciliation)"),
    _entry("UNCERTAIN_EXPOSURE", title="不确定敞口", severity="BLOCKING", domain="execution",
           explanation="存在 UNKNOWN / LOST 订单敞口 ⇒ 不允许新增暴露（降险仍允许）。",
           next_step="通过 query / reconciliation 收敛不确定订单。",
           title_en="Uncertain exposure",
           explanation_en="UNKNOWN / LOST order exposure exists, so new exposure is blocked (de-risking stays allowed)",
           next_step_en="converge uncertain orders via query / reconciliation"),
    _entry("ORDER_MULTIPLICITY_VIOLATION", title="同侧多单违规", severity="BLOCKING", domain="execution",
           explanation="同一侧存在多个 active 订单，违反单报价不变量。",
           next_step="停止新增并触发 reconciliation 收敛。",
           title_en="Order multiplicity violation",
           explanation_en="more than one active order on the same side violates the single-quote invariant",
           next_step_en="stop adding and trigger reconciliation"),
    _entry("UNKNOWN_EXPOSURE", title="敞口未知", severity="BLOCKING", domain="execution",
           explanation="无法量化的订单资料 ⇒ 敞口 UNKNOWN（不按 0）。",
           next_step="补齐订单资料或通过 reconciliation 收敛。",
           title_en="Exposure unknown",
           explanation_en="order facts are insufficient, so exposure is UNKNOWN (never treated as zero)",
           next_step_en="complete the order facts or converge via reconciliation"),
    # ------------------------------------------------------------------ rate limit
    _entry("RATE_LIMIT_NEAR_LIMIT", title="请求权重接近上限", severity="DEGRADED", domain="rate_limit",
           explanation="请求权重使用接近限额；新增暴露受到抑制。",
           next_step="降低请求频率或提高限额（数值由人类配置）。",
           title_en="Request weight near limit",
           explanation_en="request weight usage is near the limit; new exposure is suppressed",
           next_step_en="reduce request rate or raise the limit (values are human-configured)"),
    _entry("RATE_LIMIT_EXHAUSTED", title="请求权重已耗尽", severity="BLOCKING", domain="rate_limit",
           explanation="请求权重预算耗尽 ⇒ 只挡新增暴露，降险永不被阻断。",
           next_step="等待窗口重置；确认 de-risking 路径仍可用。",
           title_en="Request weight exhausted",
           explanation_en="request-weight budget is exhausted; only new exposure is blocked, de-risking is never blocked",
           next_step_en="wait for the window reset; confirm the de-risking path is still available"),
    _entry("ORDER_RATE_LIMIT_NEAR_LIMIT", title="下单速率接近上限", severity="DEGRADED", domain="rate_limit",
           explanation="订单速率使用接近限额。",
           next_step="减少下单动作（无 retry；REPLACE 不得产生第二笔写）。",
           title_en="Order rate near limit",
           explanation_en="order-rate usage is near the limit",
           next_step_en="reduce order actions (no retry; REPLACE must not create a second write)"),
    _entry("ORDER_RATE_LIMIT_EXHAUSTED", title="下单速率已耗尽", severity="BLOCKING", domain="rate_limit",
           explanation="订单速率预算耗尽 ⇒ 只挡新增暴露。",
           next_step="等待窗口重置；确认 cancel 不受影响。",
           title_en="Order rate exhausted",
           explanation_en="order-rate budget is exhausted, blocking new exposure only",
           next_step_en="wait for the window reset; confirm cancel is unaffected"),
    # ------------------------------------------------------------------ reconciliation
    _entry("RECONCILIATION_REQUIRED", title="需要 reconciliation", severity="BLOCKING", domain="reconciliation",
           explanation="出现 UNKNOWN 结果后按 policy 要求受控 reconciliation；未确认前不接受新的不确定状态。",
           next_step="通过受控入口（需 confirmation）触发 reconciliation。",
           title_en="Reconciliation required",
           explanation_en="policy requires controlled reconciliation after an UNKNOWN outcome",
           next_step_en="trigger reconciliation via the controlled entry point (confirmation required)"),
    _entry("RECONCILIATION_NOT_CONVERGED", title="reconciliation 未收敛", severity="BLOCKING",
           domain="reconciliation",
           explanation="reconcile 产生纠正动作后仍未收敛。",
           next_step="查看 reconciliation actions 与 STATUS_CONFLICT / ADOPT_REJECTED。",
           title_en="Reconciliation not converged",
           explanation_en="corrective actions were produced but the state has not converged",
           next_step_en="inspect reconciliation actions and STATUS_CONFLICT / ADOPT_REJECTED"),
    # ------------------------------------------------------------------ accounting / provider health
    _entry("ACCOUNTING_UNKNOWN", title="账本健康未知", severity="DEGRADED", domain="accounting",
           explanation="accounting 事实未接线或不可读 ⇒ UNKNOWN（不是 healthy）。",
           next_step="确认 accounting provider 是否注入且可读。",
           title_en="Accounting unknown",
           explanation_en="accounting facts are not wired or not readable (UNKNOWN, not healthy)",
           next_step_en="confirm the accounting provider is injected and readable"),
    _entry("ACCOUNTING_DEGRADED", title="账本降级", severity="DEGRADED", domain="accounting",
           explanation="accounting 部分事实缺失（如 mark / equity 未知）。",
           next_step="补齐 mark / equity 事实后重新投影。",
           title_en="Accounting degraded",
           explanation_en="some accounting facts are missing (e.g. mark / equity unknown)",
           next_step_en="supply the missing mark / equity facts"),
    # ------------------------------------------------------------------ risk
    _entry("KILL_SWITCH", title="Kill switch 生效", severity="BLOCKING", domain="risk",
           explanation="kill switch 非 NORMAL，RiskGate 拒绝新增暴露。",
           next_step="确认 kill switch 状态；cancel / reduce-only 仍按既有语义处理。",
           title_en="Kill switch active",
           explanation_en="the kill switch is not NORMAL and the RiskGate rejects new exposure",
           next_step_en="confirm kill-switch state; cancel / reduce-only keep their existing semantics"),
    _entry("BOOK_UNHEALTHY", title="盘口不健康", severity="BLOCKING", domain="risk",
           explanation="RiskGate 的盘口健康硬检查未通过。",
           next_step="查看 System → Health 的 market 健康。",
           title_en="Book unhealthy",
           explanation_en="the RiskGate hard check on book health failed",
           next_step_en="inspect market health in System → Health"),
    _entry("MISSING_MARK_PRICE", title="缺少 mark price", severity="BLOCKING", domain="risk",
           explanation="无 mark price ⇒ 无法计算敞口 / 权益（未知不等于 0）。",
           next_step="注入新鲜 mark price。",
           title_en="Missing mark price",
           explanation_en="no mark price, so exposure / equity cannot be derived (unknown != zero)",
           next_step_en="supply a fresh mark price"),
    _entry("STALE_MARK", title="mark price 过期", severity="BLOCKING", domain="risk",
           explanation="mark price 超出允许年龄。",
           next_step="刷新 mark price。",
           title_en="Stale mark price",
           explanation_en="the mark price is older than allowed",
           next_step_en="refresh the mark price"),
    _entry("MISSING_DRAWDOWN", title="缺少 drawdown 事实", severity="BLOCKING", domain="risk",
           explanation="已配置 drawdown 限额但峰值未知 ⇒ fail closed。",
           next_step="初始化 durable high-watermark。",
           title_en="Missing drawdown",
           explanation_en="a drawdown limit is configured but the peak is unknown, so it fails closed",
           next_step_en="initialize the durable high-watermark"),
    _entry("MISSING_DAILY_PNL", title="缺少当日盈亏", severity="BLOCKING", domain="risk",
           explanation="已配置 daily loss 限额但当日盈亏未知 ⇒ fail closed。",
           next_step="补齐 daily PnL 来源（income + 本地账本）。",
           title_en="Missing daily PnL",
           explanation_en="a daily-loss limit is configured but today's PnL is unknown, so it fails closed",
           next_step_en="supply the daily PnL sources (income + local ledger)"),
    _entry("UNCERTAIN_EXPOSURE_UNKNOWN", title="不确定敞口未知", severity="BLOCKING", domain="risk",
           explanation="存在无法量化的订单敞口 ⇒ 拒绝新增暴露。",
           next_step="收敛 LOST / unresolved 订单。",
           title_en="Uncertain exposure unknown",
           explanation_en="unquantifiable order exposure exists, so new exposure is rejected",
           next_step_en="converge LOST / unresolved orders"),
    _entry("POSITION_LIMIT", title="仓位限额", severity="BLOCKING", domain="risk",
           explanation="新增暴露超过 max_position_qty。",
           next_step="降低数量或调整限额（数值由人类配置）。",
           title_en="Position limit",
           explanation_en="new exposure exceeds max_position_qty",
           next_step_en="reduce quantity or adjust the limit (values are human-configured)"),
    _entry("NOTIONAL_LIMIT", title="名义价值限额", severity="BLOCKING", domain="risk",
           explanation="新增暴露超过 max_position_notional。",
           next_step="降低数量或调整限额。",
           title_en="Notional limit",
           explanation_en="new exposure exceeds max_position_notional",
           next_step_en="reduce quantity or adjust the limit"),
    _entry("OPEN_ORDER_EXPOSURE_LIMIT", title="挂单敞口限额", severity="BLOCKING", domain="risk",
           explanation="挂单敞口超过 max_open_order_exposure。",
           next_step="撤销部分挂单（降险永不被阻断）。",
           title_en="Open-order exposure limit",
           explanation_en="open-order exposure exceeds max_open_order_exposure",
           next_step_en="cancel some resting orders (de-risking is never blocked)"),
    _entry("INSUFFICIENT_AVAILABLE_BALANCE", title="可用余额不足", severity="BLOCKING", domain="risk",
           explanation="新增暴露超过可用余额（balance − open order exposure）。",
           next_step="降低数量或减少挂单。",
           title_en="Insufficient available balance",
           explanation_en="new exposure exceeds available balance (balance - open-order exposure)",
           next_step_en="reduce quantity or cancel resting orders"),
    _entry("DAILY_LOSS_LIMIT", title="当日亏损限额", severity="BLOCKING", domain="risk",
           explanation="当日已实现亏损触及限额。",
           next_step="停止新增暴露；等待 UTC 日切换或人工裁决。",
           title_en="Daily loss limit",
           explanation_en="today's realized loss reached the limit",
           next_step_en="stop new exposure; wait for the UTC day rollover or a human decision"),
    _entry("DRAWDOWN_LIMIT", title="回撤限额", severity="BLOCKING", domain="risk",
           explanation="自 activation point 的回撤触及限额。",
           next_step="停止新增暴露并评估 activation epoch。",
           title_en="Drawdown limit",
           explanation_en="drawdown since the activation point reached the limit",
           next_step_en="stop new exposure and review the activation epoch"),
    _entry("LEVERAGE_LIMIT", title="杠杆限额", severity="BLOCKING", domain="risk",
           explanation="杠杆超过 max_leverage（或未配置杠杆时按 1.0）。",
           next_step="降低仓位或调整限额。",
           title_en="Leverage limit",
           explanation_en="leverage exceeds max_leverage (or 1.0 when unconfigured)",
           next_step_en="reduce position or adjust the limit"),
    _entry("LIQUIDATION_DISTANCE", title="强平距离不足", severity="BLOCKING", domain="risk",
           explanation="与强平价的距离小于所需缓冲。",
           next_step="降低敞口。",
           title_en="Liquidation distance",
           explanation_en="the distance to liquidation is below the required buffer",
           next_step_en="reduce exposure"),
    _entry("MISSING_LIQUIDATION_INFO", title="缺少强平信息", severity="BLOCKING", domain="risk",
           explanation="已配置强平距离检查但缺少强平事实 ⇒ fail closed。",
           next_step="注入 liquidation info。",
           title_en="Missing liquidation info",
           explanation_en="a liquidation-distance check is configured but liquidation facts are missing",
           next_step_en="supply liquidation info"),
    _entry("SYMBOL_MISMATCH", title="交易对不匹配", severity="BLOCKING", domain="risk",
           explanation="提案交易对与 runtime 交易对不一致。",
           next_step="修正提案 / runtime 配置。",
           title_en="Symbol mismatch",
           explanation_en="the proposal symbol does not match the runtime symbol",
           next_step_en="fix the proposal / runtime configuration"),
    _entry("INVALID_ORDER_QUANTITY", title="数量非法", severity="BLOCKING", domain="risk",
           explanation="订单数量非法（非正 / 超范围 / 不满足规则）。",
           next_step="修正数量（本层不做隐式 round）。",
           title_en="Invalid order quantity",
           explanation_en="the order quantity is invalid (non-positive / out of range / rule violation)",
           next_step_en="fix the quantity (no implicit rounding at this layer)"),
    _entry("INVALID_ORDER_PRICE", title="价格非法", severity="BLOCKING", domain="risk",
           explanation="订单价格非法（非正 / 超范围 / 不满足规则）。",
           next_step="修正价格（tick 归一化由执行边界显式配置）。",
           title_en="Invalid order price",
           explanation_en="the order price is invalid (non-positive / out of range / rule violation)",
           next_step_en="fix the price (tick normalization is explicit at the execution boundary)"),
    _entry("REDUCE_ONLY_WOULD_INCREASE", title="reduce-only 会增大敞口", severity="BLOCKING", domain="risk",
           explanation="标记为 reduce-only 的订单实际会增大敞口 ⇒ 拒绝。",
           next_step="修正方向 / 数量。",
           title_en="Reduce-only would increase exposure",
           explanation_en="an order marked reduce-only would actually increase exposure, so it is rejected",
           next_step_en="fix the side / quantity"),
    # ------------------------------------------------------------------ orchestrator
    _entry("ORCHESTRATOR_NOT_READY", title="编排未就绪", severity="BLOCKING", domain="orchestrator",
           explanation="编排层前置条件未满足。",
           next_step="查看编排 notes 与 readiness。",
           title_en="Orchestrator not ready",
           explanation_en="orchestration preconditions are not satisfied",
           next_step_en="inspect orchestrator notes and readiness"),
    _entry("ORCHESTRATOR_RECONCILING", title="编排正在对账", severity="BLOCKING", domain="orchestrator",
           explanation="编排处于 reconciliation 中，暂停新增暴露。",
           next_step="等待 reconciliation 收敛。",
           title_en="Orchestrator reconciling",
           explanation_en="the orchestrator is reconciling; new exposure is paused",
           next_step_en="wait for reconciliation to converge"),
    _entry("AUTHORITY_INVALID", title="执行授权失效", severity="BLOCKING", domain="orchestrator",
           explanation="readiness authority 的 TTL / scope / generation 失效。",
           next_step="重新收集证据并签发新的 authority。",
           title_en="Authority invalid",
           explanation_en="the readiness authority TTL / scope / generation is no longer valid",
           next_step_en="re-collect evidence and issue a new authority"),
    _entry("EXECUTION_DISABLED", title="执行被禁用", severity="BLOCKING", domain="orchestrator",
           explanation="当前为 observe-only，写动作被记录并跳过。",
           next_step="如需写路径，显式启用（still subject to readiness/authority）。",
           title_en="Execution disabled",
           explanation_en="observe-only mode: write actions are recorded and skipped",
           next_step_en="enable writes explicitly if needed (still subject to readiness/authority)"),
    _entry("WRITE_NOT_ALLOWED", title="不允许写", severity="BLOCKING", domain="orchestrator",
           explanation="当前环境 / 模式不允许写动作。",
           next_step="确认 mode 与 environment。",
           title_en="Write not allowed",
           explanation_en="the current environment / mode does not allow write actions",
           next_step_en="confirm mode and environment"),
    _entry("RISK_REJECT", title="风险拒绝", severity="BLOCKING", domain="risk",
           explanation="RiskGate 拒绝了该提案（具体原因见同组 rejection code）。",
           next_step="查看 Activity → Risk 的具体 reason code。",
           title_en="Risk reject",
           explanation_en="the RiskGate rejected the proposal (see the specific rejection code)",
           next_step_en="inspect the specific reason code in Activity → Risk"),
    # ------------------------------------------------------------------ ops (F-12 / F-15)
    _entry("NON_LOOPBACK_NOT_ALLOWED", title="非 loopback 未获授权", severity="BLOCKING", domain="network",
           explanation="bind 地址不是 loopback，且未显式 opt-in；为避免意外暴露，拒绝启动。",
           next_step="改用 127.0.0.1，或显式 --allow-non-loopback 并配置 bearer token。",
           title_en="Non-loopback bind not allowed",
           explanation_en="the bind address is not loopback and opt-in was not given, so startup is refused",
           next_step_en="bind 127.0.0.1, or pass --allow-non-loopback together with a bearer token"),
    _entry("AUTH_TOKEN_REQUIRED", title="非 loopback 需要认证", severity="BLOCKING", domain="auth",
           explanation="非 loopback 部署必须配置 bearer token；缺 token 一律拒绝启动（不做‘警告后继续’）。",
           next_step="用 --auth-token-ref env:PROBEX_API_TOKEN 指定 secret 引用，并在环境中提供该变量。",
           title_en="Authentication required for non-loopback",
           explanation_en="a non-loopback deployment must configure a bearer token; missing token refuses startup",
           next_step_en="use --auth-token-ref env:PROBEX_API_TOKEN and provide the variable in the environment"),
    _entry("AUTH_TOKEN_MISSING", title="缺少 bearer token", severity="BLOCKING", domain="auth",
           explanation="非 loopback API 的所有 /api/v1/* 都需要 `Authorization: Bearer <token>`。",
           next_step="在请求头带上正确 token（值不会出现在日志/快照/审计中）。",
           title_en="Missing bearer token",
           explanation_en="every /api/v1/* call on a non-loopback deployment needs Authorization: Bearer <token>",
           next_step_en="send the token header (the value never appears in logs/snapshots/audit)"),
    _entry("AUTH_TOKEN_INVALID", title="bearer token 无效", severity="BLOCKING", domain="auth",
           explanation="提供的 bearer token 与配置的 secret 不匹配（比较使用常量时间）。",
           next_step="核对 secret 引用与部署环境；失败详情不包含 token 内容。",
           title_en="Invalid bearer token",
           explanation_en="the provided bearer token does not match the configured secret (constant-time compare)",
           next_step_en="check the secret reference and deployment environment; failures never include token material"),
    _entry("RETENTION_UNBOUNDED", title="Retention 未配置（UNBOUNDED）", severity="DEGRADED", domain="retention",
           explanation="未配置任何 durable retention 参数 ⇒ 存量不设上限，且**不会偷偷删除**任何东西。",
           next_step="如需有界，显式给出 retention.run_max_runs / retention.run_max_age_ms 等参数。",
           title_en="Retention unbounded",
           explanation_en="no durable retention parameter is configured, so nothing is ever deleted implicitly",
           next_step_en="set retention.run_max_runs / retention.run_max_age_ms explicitly to bound growth"),
    _entry("RETENTION_PRUNED", title="Retention 已执行", severity="INFO", domain="retention",
           explanation="按显式 policy 删除了已完成的旧 run（record 文件 + 索引压缩）；active run 永不删除。",
           next_step="在 System → Ops → Retention 查看 last prune 与保留计数。",
           title_en="Retention pruned finished runs",
           explanation_en="old finished runs were removed per the explicit policy (active run is never removed)",
           next_step_en="review last prune and kept counts in System → Ops → Retention"),
    _entry("RETENTION_NOOP", title="Retention 无匹配", severity="INFO", domain="retention",
           explanation="policy 已执行但没有 run 匹配删除规则（或 policy 为 UNBOUNDED）。",
           next_step="无需操作。",
           title_en="Retention no-op",
           explanation_en="the policy ran but nothing matched the prune rule (or the policy is unbounded)",
           next_step_en="no action required"),
    _entry("LOG_SINK_UNBOUNDED", title="日志 sink 未设上限", severity="DEGRADED", domain="logging",
           explanation="日志输出到 stderr（由外部采集）或文件未配置轮转；进程自身不保留日志。",
           next_step="如需轮转，配置 retention.log_max_bytes / retention.log_backup_count 与 PROBEX_LOG_FILE。",
           title_en="Log sink unbounded",
           explanation_en="logs go to stderr (collected externally) or a file without rotation; the process keeps none",
           next_step_en="set retention.log_max_bytes / retention.log_backup_count with PROBEX_LOG_FILE for rotation"),
    _entry("PROCESS_LIVE_READINESS_BLOCKED", title="进程活着但不可交易", severity="DEGRADED", domain="process",
           explanation="liveness 只表示服务进程活着；trade readiness 由独立的 gate 决定，可以 fail-closed。",
           next_step="查看 System → Readiness 与 Process liveness 两栏，二者互不替代。",
           title_en="Process live but trade readiness blocked",
           explanation_en="liveness only means the process is alive; trade readiness is decided separately and may fail closed",
           next_step_en="compare System → Readiness with Process liveness; neither substitutes for the other"),
    _entry("FEED_SOURCE_FAILED", title="行情源失败", severity="BLOCKING", domain="market",
           explanation="真实 feed / 外部事实源读取失败；市场事实按既有语义失效（不伪造健康）。",
           next_step="查看 market feed 日志与 event store 路径。",
           title_en="Feed source failed",
           explanation_en="the real feed / external fact source failed; market facts degrade per existing semantics",
           next_step_en="inspect the market feed log and the event store path"),
    _entry("RUNTIME_FAILED", title="Runtime 失败", severity="BLOCKING", domain="process",
           explanation="runtime 异常终止，run 记为 INCOMPLETE（不伪造 COMPLETED）。",
           next_step="查看 shutdown/run_failure 日志与 durable run record。",
           title_en="Runtime failed",
           explanation_en="the runtime terminated abnormally; the run is recorded INCOMPLETE (never COMPLETED)",
           next_step_en="inspect the shutdown/run_failure log and the durable run record"),
    # ------------------------------------------------------------------ config
    _entry("CONFIG_ENTRY_UNKNOWN", title="配置项未知", severity="DEGRADED", domain="config",
           explanation="该配置项没有候选来源（业务值不得有隐式默认）。",
           next_step="在 CLI / ENV / FILE / CONSTRUCTOR 之一显式提供。",
           title_en="Config entry unknown",
           explanation_en="no candidate source exists for this config entry (no implicit defaults)",
           next_step_en="provide it explicitly via CLI / ENV / FILE / CONSTRUCTOR"),
    _entry("CONFIG_SECRET_REF_ONLY", title="secret 仅有引用", severity="INFO", domain="config",
           explanation="secret 值从不进入 provenance，只记录引用名（如 env:BINANCE_API_KEY）。",
           next_step="在环境中提供该变量；不要期望在配置视图看到值。",
           title_en="Secret reference only",
           explanation_en="secret values never enter provenance; only the reference name is recorded",
           next_step_en="provide the variable in the environment; do not expect the value in the config view"),
)

CATALOG: dict[str, ReasonExplanation] = dict(_ENTRIES)


def lookup(reason_code: str) -> ReasonExplanation | None:
    """精确查找（未收录 ⇒ None，绝不返回近似的猜测）。"""
    if not isinstance(reason_code, str):
        raise TypeError("lookup() requires a reason code string")
    return CATALOG.get(reason_code)


def explain_reason(reason_code: object) -> ReasonExplanation:
    """总是返回一个解释：已收录 ⇒ 目录文案；未收录 ⇒ 原始 code + 暂无解释。"""
    code = str(reason_code)
    found = CATALOG.get(code)
    if found is not None:
        return found
    return ReasonExplanation(reason_code=code, title=UNKNOWN_TITLE, explanation=UNKNOWN_EXPLANATION,
                             severity="UNKNOWN", suggested_next_step=UNKNOWN_NEXT_STEP,
                             domain="unknown", title_en="no explanation available",
                             explanation_en=UNKNOWN_EXPLANATION_EN,
                             suggested_next_step_en=UNKNOWN_NEXT_STEP_EN, catalogued=False)


def catalog_payload() -> tuple[dict[str, object], ...]:
    """按 code 排序的稳定目录载荷（API / UI / CLI / Assistant 共用）。"""
    return tuple(CATALOG[code].to_payload() for code in sorted(CATALOG))


def explain_codes(codes: object) -> dict[str, dict[str, object]]:
    """为一批 code 生成解释映射（去重、按 code 排序；未知 code 保留原始 key）。"""
    unique = sorted({str(code) for code in (codes or ()) if str(code)})
    return {code: explain_reason(code).to_payload() for code in unique}


__all__ = [
    "CATALOG", "DOMAINS", "ReasonExplanation", "UNKNOWN_EXPLANATION", "UNKNOWN_NEXT_STEP",
    "UNKNOWN_TITLE", "catalog_payload", "explain_codes", "explain_reason", "lookup",
]
